from slack.Slack import Slack
from .WawMaps import WawMaps
import time

class Christmaswarehouse(WawMaps):

	def install(self, output=None):
		if output == None:
			print('mapname = ' + self.mapname)
			print('homepage = ' + self.homepage)
			print('map_homepage = ' + self.map_homepage)
			print('Installing Files/Scripts')
			## subproccess.call([C:\\Desktop\christmaswarehouse.exe])
			time.sleep(2)
			print('Creating Ported Black Ops 2 Weapons')
			time.sleep(2)
			print('Creating Ported Halo Weapons')
			time.sleep(2)
			print('Creating Christmas Theme')
			time.sleep(2)
			print('Creating Ammomatic Machine (Yep its in this map)')
			time.sleep(2)
			print('Christmas Warehouse Successfuly Installed')
			Slack.send_message('#coding', 'Map Installed: Christmas Warehouse')
		else:
			output.delete(1.0, END)
			output.insert(INSERT, 'mapname = ' + self.mapname + '\n')
			output.update_idletasks()
			output.insert(END, 'homepage = ' + self.homepage + '\n')
			output.update_idletasks()
			output.insert(END, 'map_homepage = ' + self.map_homepage + '\n')
			output.update_idletasks()
			## subprocess.call(["c:\\Desktop\Zombie/ Cargo.exe"])
			output.insert(END, 'Installing Files/Scripts\n')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Creating Ported Black Ops 2 Weapons\n')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Creating Ported Halo Weapons\n')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Creating Christmas Theme\n')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Creating Ammomatic Machine\n')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Family Guy Zombies Successfuly Installed')
			output.update_idletasks()
			Slack.send_message('#coding', 'Map Installed through UI: Christmas Warehouse')

	def uninstall(self):
		print('mapname = ' + self.mapname)
		print('Removing Files/Scripts')
		time.sleep(2)
		print('Removing Ported Black Ops 2 Weapons')
		time.sleep(2)
		print('Removing Ported Halo Weapons')
		time.sleep(2)
		print('Removing Christmas Theme')
		time.sleep(2)
		print('Removing Ammomatic Themes and Files')
		time.sleep(2)
		print('Christmas Warehouse Uninstalled with No Errors')

	def description(self):
		print('mapname = ' + self.mapname)
		print('homepage = ' + self.homepage)
		print('map_homepage = ' + self.map_homepage)
		print('- Custom Files/Scripts')
		print('- Ported Halo Weapons')
		print('- Ported Black Ops 2 Weapons')
		print('- Ammomatic Perk')
		print('- Custom Mystery Box Prefab')
		print('- Custom Perks')
		print('- Christmas Theme')