import time
from .WawMaps import WawMaps
from slack.Slack import Slack

class Cryogenic(WawMaps):

	def install(self, output=None):
		if output == None:
			print('mapname = ' + self.mapname)
			print('homepage = ' + self.homepage)
			print('map_homepage = ' + self.map_homepage)
			## subprocess.call(["c:\\Desktop\cryogenic.exe"])
			print('Installing Files/Scripts')
			time.sleep(2)
			print('Creating FX and Images')
			time.sleep(3)
			print('Setting Blood Rain')
			time.sleep(2)
			print('Cyrogenic now Sucessfuly Installed')
			Slack.send_message('#coding', 'Map Installed: Cyrogenic')
		else:
			output.delete(1.0, END)
			output.insert(INSERT, 'mapname = ' + self.mapname + '\n')
			output.update_idletasks()
			output.insert(END, 'homepage = ' + self.homepage + '\n')
			output.update_idletasks()
			output.insert(END, 'map_homepage = ' + self.map_homepage + '\n')
			output.update_idletasks()
			## subprocess.call(["c:\\Desktop\cyrogenic.exe"])
			time.sleep(2)
			output.insert(END, 'Installing Files\n')
			output.update_idletasks()
			time.sleep(4)
			output.insert(END, 'Creating Images\n')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Background Images\n')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Installing FX\n')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Creating Blood Rain')
			output.update_idletasks()
			time.sleep(2)
			output.insert(END, 'Cyrogenic Successfuly Installed')
			output.update_idletasks()
			Slack.send_message('#coding', 'Map Installed through UI: Cyrogenic')

	def uninstall(self):
		print('Removing Files/Scripts')
		time.sleep(2)
		print('Cryogenic Map Uninstalled with No Errors')

	def description(self):
		print('mapname = ' + self.mapname)
		print('homepage = ' + self.homepage)
		print('map_homepage = ' + self.map_homepage)
		print('- 9 Perks')
		print('- Custom Voice Overs')
		print('- Mob of the Dead Cutom Zombies')
		print('- Halo Weapons')
		print('- Nuketown 2025 Player Models')
		print('- Snowing Blood')
		print('- Buyable Ending')
		print('- Buyable Max Ammo and Double Points')
		print('- Double Tap 2.0')
		print('- Zombie Counter')
		print('- Verrukt Sprinters')
		print('- Five Style Teleporters')
		print('- Laser Trap')
		print('- Ride-able Centrifuge')
		print('- Fan Blade List')
		print('')
		print('Weapons List:')
		print('Thundergun')
		print('Scavanger')
		print('Blundergat')
		print('Acidgat')
		print('Commando')
		print('FAL')
		print('Galil')
		print('Honeybadger')
		print('AE4')
		print('Ray Gun')
		print('PPSH')
		print('M2 Flamethrower')
		print('Wudnerwaffe')
		print('Halo Energy Sword')
		print('Halo Battle Rifle')
		print('Halo DMR')
		print('Halo Magnum')